version: '3.8'

services:
  api-rest:
    image: node:fermium-alpine
    command: npm run start:dev
    restart: always
    volumes:
      - ./:/app
    ports:
      - 3010:3000

    working_dir: /app
